"""Adiciona tabela de historico de status do projeto,status e tipo de projeto

Revision ID: 5a2f34b451bb
Revises: c7ac1197458f
Create Date: 2025-06-24 23:10:32.104792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2f34b451bb'
down_revision: Union[str, Sequence[str], None] = 'c7ac1197458f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_status_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_anterior', sa.Enum('LEVANTAMENTO_REQUISITOS', 'RECEBIMENTO_BASES', 'CONSTRUCAO_PIPELINE', 'PRIMEIRA_VERSAO', 'AJUSTES', 'DOCUMENTACAO', 'AJUSTES_FINOS', 'FINALIZADO', name='statusprojeto'), nullable=True),
    sa.Column('status_novo', sa.Enum('LEVANTAMENTO_REQUISITOS', 'RECEBIMENTO_BASES', 'CONSTRUCAO_PIPELINE', 'PRIMEIRA_VERSAO', 'AJUSTES', 'DOCUMENTACAO', 'AJUSTES_FINOS', 'FINALIZADO', name='statusprojeto'), nullable=False),
    sa.Column('data_mudanca', sa.DateTime(), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validacoes_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('o_que_sentiu_falta', sa.String(), nullable=True),
    sa.Column('o_que_tiraria', sa.String(), nullable=True),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projetos', sa.Column('tipo_projeto', sa.Enum('AUTOMACAO', 'DASHBOARD', 'ANALISE_ESTATISTICA', 'SOFTWARE', 'VISAO_COMPUTACIONAL', 'CLASSIFICACAO', 'REGRESSAO', 'OUTROS', name='tipoprojeto'), nullable=True))
    op.add_column('projetos', sa.Column('status_projeto', sa.Enum('LEVANTAMENTO_REQUISITOS', 'RECEBIMENTO_BASES', 'CONSTRUCAO_PIPELINE', 'PRIMEIRA_VERSAO', 'AJUSTES', 'DOCUMENTACAO', 'AJUSTES_FINOS', 'FINALIZADO', name='statusprojeto'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'status_projeto')
    op.drop_column('projetos', 'tipo_projeto')
    op.drop_table('validacoes_projeto')
    op.drop_table('historico_status_projeto')
    # ### end Alembic commands ###
