"""Adiciona coluna de skills a tabela de projetos

Revision ID: 0a802b9e7e19
Revises: 5a2f34b451bb
Create Date: 2025-06-27 22:14:25.250663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a802b9e7e19'
down_revision: Union[str, Sequence[str], None] = '5a2f34b451bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('skills', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'skills')
    # ### end Alembic commands ###
