"""Criação inicial das tabelas cliente, produto e projeto

Revision ID: c7ac1197458f
Revises: 
Create Date: 2025-06-24 00:09:52.588042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ac1197458f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('nivel_estatistico', sa.Enum('BASICO', 'INTERMEDIARIO', 'AVANCADO', 'ESPECIALISTA', name='nivelconhecimento'), nullable=True),
    sa.Column('usuario_final', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_produto')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_projeto', sa.String(), nullable=False),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('desempenho_atual', sa.String(), nullable=True),
    sa.Column('como_e_cobrado', sa.String(), nullable=True),
    sa.Column('o_que_prejudica_objetivo', sa.String(), nullable=True),
    sa.Column('metrica_avaliacao', sa.String(), nullable=True),
    sa.Column('como_melhorar_desempenho', sa.String(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projetos')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
